"""drop service domain, decoded sts fields on listing

Revision ID: 2be02df9d286
Revises: 0d70da5652b7
Create Date: 2026-08-27 09:52:12.361039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2be02df9d286'
down_revision: Union[str, Sequence[str], None] = '0d70da5652b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spare_parts')
    op.drop_table('cars')
    op.drop_table('review')
    op.add_column('sale_cars', sa.Column('mark', sa.String(), nullable=True))
    op.add_column('sale_cars', sa.Column('model', sa.String(), nullable=True))
    op.add_column('sale_cars', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('sale_cars', sa.Column('transmission', sa.String(), nullable=True))
    op.add_column('sale_cars', sa.Column('engine_power', sa.Integer(), nullable=True))
    op.drop_column('sale_cars', 'chroma_document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_cars', sa.Column('chroma_document_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sale_cars', 'engine_power')
    op.drop_column('sale_cars', 'transmission')
    op.drop_column('sale_cars', 'year')
    op.drop_column('sale_cars', 'model')
    op.drop_column('sale_cars', 'mark')
    op.create_table('review',
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('chroma_document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('review_user_id_fkey')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('review_pkey')),
    sa.UniqueConstraint('chroma_document_id', name=op.f('review_chroma_document_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cars',
    sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('car_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chroma_document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sts_photos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cars_user_id_fkey'),
    sa.PrimaryKeyConstraint('car_id', name='cars_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('spare_parts',
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('car_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mileage_last_replaced', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('array_mileage', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('mileage_average_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chroma_document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], name=op.f('spare_parts_car_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('spare_parts_user_id_fkey')),
    sa.PrimaryKeyConstraint('part_id', name=op.f('spare_parts_pkey'))
    )
    # ### end Alembic commands ###
