"""~user

Revision ID: 6a21a5af628e
Revises: 87e00d9fd13e
Create Date: 2026-03-15 04:07:33.726995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a21a5af628e'
down_revision: Union[str, Sequence[str], None] = '87e00d9fd13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('guest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_column('users', 'guest_json')
    op.drop_column('users', 'device_id')
    # ### end Alembic commands ###
