"""car catalogue with aliases and suggestions

Revision ID: a1c7f3d90b42
Revises: 2be02df9d286
Create Date: 2026-08-27

Written by hand rather than autogenerated: the pg_trgm extension and its GIN indexes
are what make the fuzzy step of the matching ladder possible, and Alembic's autogenerate
sees neither an extension nor an operator-class index.

The two name columns added in story 1 become foreign keys here. Their values are not
migrated: catalogue rows do not exist yet at this point, and the seeder that creates
them runs after. Any listing already carrying a decoded make keeps it in mark_raw, which
is where the resolver looks, so nothing is lost -- the rows simply appear as unresolved
spellings in the moderation queue once the catalogue is seeded.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1c7f3d90b42"
down_revision: Union[str, Sequence[str], None] = "2be02df9d286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "brands",
        sa.Column("brand_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name_ru", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("is_popular", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.PrimaryKeyConstraint("brand_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_brands_slug", "brands", ["slug"])

    op.create_table(
        "car_models",
        sa.Column("model_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("brand_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.brand_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("model_id"),
        sa.UniqueConstraint("brand_id", "slug", name="car_models_brand_slug_key"),
    )
    op.create_index("ix_car_models_brand_id", "car_models", ["brand_id"])
    op.create_index("ix_car_models_slug", "car_models", ["slug"])

    op.create_table(
        "brand_aliases",
        sa.Column("alias_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("brand_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("alias_norm", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.brand_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("alias_norm"),
    )
    op.create_index("ix_brand_aliases_brand_id", "brand_aliases", ["brand_id"])
    op.create_index("ix_brand_aliases_alias_norm", "brand_aliases", ["alias_norm"])

    op.create_table(
        "model_aliases",
        sa.Column("alias_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("model_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("brand_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("alias_norm", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["car_models.model_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.brand_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias_id"),
        sa.UniqueConstraint("brand_id", "alias_norm", name="model_aliases_brand_alias_key"),
    )
    op.create_index("ix_model_aliases_model_id", "model_aliases", ["model_id"])
    op.create_index("ix_model_aliases_brand_id", "model_aliases", ["brand_id"])

    op.create_table(
        "catalog_suggestions",
        sa.Column("suggestion_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("brand_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("raw_norm", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False, server_default="pending"),
        sa.Column("resolved_brand_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolved_model_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolved_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.brand_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_brand_id"], ["brands.brand_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolved_model_id"], ["car_models.model_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("suggestion_id"),
        sa.UniqueConstraint("kind", "brand_id", "raw_norm", name="catalog_suggestions_unique_raw"),
    )
    op.create_index("ix_catalog_suggestions_brand_id", "catalog_suggestions", ["brand_id"])
    op.create_index("ix_catalog_suggestions_raw_norm", "catalog_suggestions", ["raw_norm"])
    op.create_index("ix_catalog_suggestions_status", "catalog_suggestions", ["status"])

    # The fuzzy step of the ladder runs similarity() over these two columns. Without a
    # GIN trigram index every unresolved spelling is a sequential scan of the catalogue,
    # which is cheap at 71 brands and stops being cheap as models grow.
    op.execute("CREATE INDEX ix_brands_slug_trgm ON brands USING gin (slug gin_trgm_ops)")
    op.execute("CREATE INDEX ix_car_models_slug_trgm ON car_models USING gin (slug gin_trgm_ops)")

    op.add_column("sale_cars", sa.Column("brand_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column("sale_cars", sa.Column("model_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column("sale_cars", sa.Column("mark_raw", sa.String(), nullable=True))
    op.add_column("sale_cars", sa.Column("model_raw", sa.String(), nullable=True))

    # Whatever decode_vin had already written is a raw spelling, not a catalogue key.
    op.execute("UPDATE sale_cars SET mark_raw = mark, model_raw = model")

    op.drop_column("sale_cars", "mark")
    op.drop_column("sale_cars", "model")

    op.create_index("ix_sale_cars_brand_id", "sale_cars", ["brand_id"])
    op.create_index("ix_sale_cars_model_id", "sale_cars", ["model_id"])
    op.create_foreign_key(
        "sale_cars_brand_id_fkey", "sale_cars", "brands", ["brand_id"], ["brand_id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        "sale_cars_model_id_fkey", "sale_cars", "car_models", ["model_id"], ["model_id"], ondelete="SET NULL"
    )


def downgrade() -> None:
    op.drop_constraint("sale_cars_model_id_fkey", "sale_cars", type_="foreignkey")
    op.drop_constraint("sale_cars_brand_id_fkey", "sale_cars", type_="foreignkey")
    op.drop_index("ix_sale_cars_model_id", table_name="sale_cars")
    op.drop_index("ix_sale_cars_brand_id", table_name="sale_cars")

    op.add_column("sale_cars", sa.Column("mark", sa.String(), nullable=True))
    op.add_column("sale_cars", sa.Column("model", sa.String(), nullable=True))
    op.execute("UPDATE sale_cars SET mark = mark_raw, model = model_raw")

    op.drop_column("sale_cars", "model_raw")
    op.drop_column("sale_cars", "mark_raw")
    op.drop_column("sale_cars", "model_id")
    op.drop_column("sale_cars", "brand_id")

    op.drop_table("catalog_suggestions")
    op.drop_table("model_aliases")
    op.drop_table("brand_aliases")
    op.drop_table("car_models")
    op.drop_table("brands")

    # pg_trgm is left installed: another migration or a hand-run query may rely on it,
    # and dropping an extension is not the business of the migration that added a table.
