"""listing draft and lifecycle statuses

Revision ID: b7e1c4a2f905
Revises: a1c7f3d90b42
Create Date: 2026-08-28

Written by hand rather than autogenerated: the data step matters more than the schema
step. Autogenerate sees the three columns becoming nullable and the two new ones, but
not that every existing row carries a status value that no longer exists.

on_sale is retired, not renamed: the listing that was on sale is exactly the listing
that is published, and keeping both spellings would leave the feed filtering on one of
them forever.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b7e1c4a2f905"
down_revision: Union[str, Sequence[str], None] = "a1c7f3d90b42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column("sale_cars", "price", existing_type=sa.Float(), nullable=True)
    op.alter_column("sale_cars", "milleage", existing_type=sa.Float(), nullable=True)
    op.alter_column("sale_cars", "phone_number", existing_type=sa.String(), nullable=True)

    op.add_column("sale_cars", sa.Column("reject_reason", sa.Text(), nullable=True))
    op.add_column("sale_cars", sa.Column("published_at", sa.DateTime(), nullable=True))

    op.execute("UPDATE sale_cars SET status = 'published' WHERE status = 'on_sale'")
    op.execute("UPDATE sale_cars SET published_at = created_at WHERE status = 'published'")

    op.alter_column("sale_cars", "status", server_default="draft")
    op.create_index("ix_sale_cars_status", "sale_cars", ["status"])


def downgrade() -> None:
    op.drop_index("ix_sale_cars_status", table_name="sale_cars")
    op.alter_column("sale_cars", "status", server_default="on_sale")

    # The four statuses added by this story have no pre-story equivalent. A draft was not
    # expressible before, so downgrading has to choose: everything not sold goes back to
    # on_sale, which is what the single pre-story alternative meant.
    op.execute("UPDATE sale_cars SET status = 'on_sale' WHERE status <> 'sold'")

    op.drop_column("sale_cars", "published_at")
    op.drop_column("sale_cars", "reject_reason")

    op.execute("UPDATE sale_cars SET price = 0 WHERE price IS NULL")
    op.execute("UPDATE sale_cars SET milleage = 0 WHERE milleage IS NULL")
    op.execute("UPDATE sale_cars SET phone_number = '' WHERE phone_number IS NULL")

    op.alter_column("sale_cars", "phone_number", existing_type=sa.String(), nullable=False)
    op.alter_column("sale_cars", "milleage", existing_type=sa.Float(), nullable=False)
    op.alter_column("sale_cars", "price", existing_type=sa.Float(), nullable=False)
