"""sync_models_after_restore

Revision ID: c850a7064673
Revises: 41ba0a77882c
Create Date: 2026-02-26 15:09:24.734834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c850a7064673'
down_revision: Union[str, Sequence[str], None] = '41ba0a77882c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_table('appointments')
    op.execute('DROP TABLE repairs CASCADE')
    op.drop_column('review', 'repairs_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('repairs_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('review_repairs_id_fkey'), 'review', 'repairs', ['repairs_id'], ['repairs_id'], ondelete='CASCADE')
    op.create_table('repairs',
    sa.Column('repairs_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('phones', postgresql.ARRAY(sa.VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_hours', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work_days', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='repairs_user_id_fkey'),
    sa.PrimaryKeyConstraint('repairs_id', name='repairs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repairs_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('car_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('problem_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.car_id'], name=op.f('appointments_car_id_fkey')),
    sa.ForeignKeyConstraint(['repairs_id'], ['repairs.repairs_id'], name=op.f('appointments_repairs_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('appointments_user_id_fkey')),
    sa.PrimaryKeyConstraint('appointment_id', name=op.f('appointments_pkey'))
    )
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_table('schedules',
    sa.Column('schedules_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repairs_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_start', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time_end', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('break_start', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('break_end', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['repairs_id'], ['repairs.repairs_id'], name=op.f('schedules_repairs_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('schedules_user_id_fkey')),
    sa.PrimaryKeyConstraint('schedules_id', name=op.f('schedules_pkey'))
    )
    # ### end Alembic commands ###
